### ISSUE TITLE
Update the background image (again)

### ISSUE THREAD

**Issue by ethanluoyc** [ethanluoyc/yechuandanmu#2]
@JoeyTeng The addition of the logo on the right hand side feels off. We can probably strip that completely since we have one on the left (upon toggling to display, of course)

Maybe we can ask Zhuoyu to provide a copy of the background without the logo? Or maybe ask her whether she thinks the current implementation is okay.

Once we fix on the look, we can proceed to the next stage of testing. You can check out load-testing.sh for inspiration (it uses Apache Bench)

**Comment by JoeyTeng** [comment]
@ethanluoyc Okay, I think they could provide a version without the logo. I just sent the email.

**Comment by ethanluoyc** [comment]
Great! Thanks!

Sent from my iPhone, sorry for the brevity.

On Mon, Jul 11, 2016 at 8:11 PM +0800, "Joey Teng" notifications@github.com wrote:

@ethanluoyc Okay, I think they could provide a version without the logo. I just sent the email.

**Comment by JoeyTeng** [comment]
Reply so fast...

**Comment by ethanluoyc** [comment]
Hhh I was reading it on my phone

Sent from my iPhone, sorry for the brevity.

On Mon, Jul 11, 2016 at 8:13 PM +0800, "Joey Teng" notifications@github.com wrote:

Reply so fast...

**Comment by JoeyTeng** [comment]
Are you using any app? I also want to use Github on iPhone, but I cannot find a proper app...

**Comment by ethanluoyc** [comment]
Nope. I'm just using Outlook for iOS, quite an elegant piece of software from Microsoft :)

Sent from my iPhone, sorry for the brevity.

On Mon, Jul 11, 2016 at 8:15 PM +0800, "Joey Teng" notifications@github.com wrote:

Are you using any app? I also want to use Github on iPhone, but I cannot find a proper app...

**Comment by JoeyTeng** [comment]
Oh so basically just reply through email?

**Comment by ethanluoyc** [comment]
Yep

Sent from my iPhone, sorry for the brevity.

On Mon, Jul 11, 2016 at 8:17 PM +0800, "Joey Teng" notifications@github.com wrote:

Oh so basically just reply through email?

**Comment by JoeyTeng** [comment]
Okay. Thanks!

**Comment by ethanluoyc** [comment]
Outlook has two mailboxes, one with priority. The issues I follow get to the priority box and I only set notifications for my priority mailbox

Sent from my iPhone, sorry for the brevity.

On Mon, Jul 11, 2016 at 8:17 PM +0800, "Yicheng Luo" ethanluoyc@gmail.com wrote:

Yep

Sent from my iPhone, sorry for the brevity.

On Mon, Jul 11, 2016 at 8:17 PM +0800, "Joey Teng" notifications@github.com wrote:

Oh so basically just reply through email?

**Comment by JoeyTeng** [comment]
#3

**Comment by JoeyTeng** [comment]
#3 Please merge this PR.
