### ISSUE TITLE
Multiple Check will cause multiple sending of danmu

### ISSUE THREAD

**Issue by JoeyTeng** [ethanluoyc/yechuandanmu#6]
If more than one client are in check page, they give different status on one danmu and will cause repeating sending.

**Comment by ethanluoyc** [comment]
It should be a bug in the backend logic, I will check that and fix it

**Comment by JoeyTeng** [comment]
Okay, thanks:)

**Comment by ethanluoyc** [comment]
I am closing this since I have fixed it in a recent post to master (see 618761e). But please kindly help me test it. Reopen this issue if the fix does not work.
