### ISSUE TITLE
Danmu player: Font size and danmu covering

### ISSUE THREAD

**Issue by JoeyTeng** [ethanluoyc/yechuandanmu#7]
1. Could not change the font size of danmu.
2. Danmu will cover each other (Nico-Nico style). Need an option to switch to "bilibili style" (prevent covering)

**Comment by ethanluoyc** [comment]
This is a rather complex issue. I currently use an open library for the Danmu, which means that the logic for displaying the Danmus are handled by that library. I want to write a danmaku player myself but haven't not find the time to do it. Let me think about it and get you back on this

**Comment by JoeyTeng** [comment]
I find the configuration in "danmu.js", I think we could edit that. E.g,
currently the height and font size are randomly chosen by the program, we
may add a variable to save the lowest height without overlapping.

**Comment by ethanluoyc** [comment]
I'm a bit confused as to why setting the lowest height can fix it. I haven't taken a look into danmu.js for quite some time. But if u are confident that this will fix the problem. Feel free to amend it and fix it (so we can close this)
Sent from my iPhone, sorry for the brevity.

On Thu, Jul 21, 2016 at 10:10 AM +0800, "Joey Teng" notifications@github.com wrote:

I find the configuration in "danmu.js", I think we could edit that. E.g,

currently the height and font size are randomly chosen by the program, we

may add a variable to save the lowest height without overlapping.

**Comment by JoeyTeng** [comment]
I mean the height for one certain danmu. I will check the grammar of js and
try it these days.

**Comment by ethanluoyc** [comment]
Thanks, sorry for not being able to help you a lot these few days. Traveling.

Sent from my iPhone, sorry for the brevity.

On Thu, Jul 21, 2016 at 10:14 AM +0800, "Joey Teng" notifications@github.com wrote:

I mean the height for one certain danmu. I will check the grammar of js and

try it these days.

**Comment by JoeyTeng** [comment]
It's okay. Have a nice trip!

**Comment by JoeyTeng** [comment]
I have use a tricky way to mitigate overlapping problem. Font size is not emergent now.
